"""empty message

Revision ID: b719f493413e
Revises: 
Create Date: 2019-04-17 23:32:58.621020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b719f493413e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_mobile', sa.String(length=20), nullable=True),
    sa.Column('phone_fix', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Unicode(length=255), nullable=True),
    sa.Column('zipcode', sa.String(length=20), nullable=True),
    sa.Column('city', sa.Unicode(length=128), nullable=True),
    sa.Column('country', sa.Unicode(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=True)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('firstname', sa.Unicode(length=64), nullable=True),
    sa.Column('lastname', sa.Unicode(length=64), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('birthcity', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_username'), 'profile', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_username'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
